version: '2'
services:
  pm_app-app:
    image: pm_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://pm_app-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=pm_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  pm_app-mongodb:
    extends:
      file: mongodb.yml
      service: pm_app-mongodb
